---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: react-app-image-update
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: flux@example.com
        name: flux
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: react-app-source
  update:
    path: ./manifests
    strategy: Setters
