---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: react-app-img-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react-app-img-repo
  policy:
    semver:
      range: 1.x.0
