---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: react-app-source
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/wissemkhr/react-k8s-repo
